spring:
  application:
    name: activityservice
  data:
    mongodb:
      uri: mongodb+srv://dineshpandey3536:3HYP52HzgpXSk1b5@cluster0.ktglbgt.mongodb.net/microservices_activities


server:
  port: 8082