spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb+srv://dineshpandey3536:3HYP52HzgpXSk1b5@cluster0.ktglbgt.mongodb.net/microservices_activities


server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/