spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888

# JVM arguments to suppress native access warnings
jvm:
  args: --enable-native-access=ALL-UNNAMED